### ISSUE TITLE
Sink Feedback for Carrier is incorrect

### ISSUE THREAD

**Issue by Psypher9** [EthanHair/destroyers#1]
When I sank the carrier, the image for the Destroyer showed as sunk (image attached below). I can also see that there are no other possibilities for another ship to be vertical at the end of the carrier, where the submarine and carrier meet.

When I sink a ship, the correct ship should be marked as sunk

![image](https://user-images.githubusercontent.com/15854173/209365393-e5ad4ff5-c946-4863-a578-bce2cf5ab557.png)

**Comment by EthanHair** [comment]
I think that there is another ship that is vertical along the right wall and that is why it says the destroyer is destroyed and not the carrier
